version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  multiarch-build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          name: "foo"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "arm-${CIRCLE_SHA1}"
          platform: linux/arm64
      - aws-ecr/build-and-push-image:
          name: "bar"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "x86-${CIRCLE_SHA1}"
          platform: linux/amd64

workflows:
  version: 2
  multi-arch-deploy:
    jobs:
      - multiarch-build